/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    services: Service;
    'portfolio-categories': PortfolioCategory;
    portfolio: Portfolio;
    'catalog-categories': CatalogCategory;
    catalog: Catalog;
    reviews: Review;
    'team-members': TeamMember;
    vacancies: Vacancy;
    requests: Request;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'portfolio-categories': PortfolioCategoriesSelect<false> | PortfolioCategoriesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    'catalog-categories': CatalogCategoriesSelect<false> | CatalogCategoriesSelect<true>;
    catalog: CatalogSelect<false> | CatalogSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    vacancies: VacanciesSelect<false> | VacanciesSelect<true>;
    requests: RequestsSelect<false> | RequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contacts-page': ContactsPage;
    'services-page': ServicesPage;
    'portfolio-page': PortfolioPage;
    'catalog-page': CatalogPage;
    'blog-page': BlogPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contacts-page': ContactsPageSelect<false> | ContactsPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'portfolio-page': PortfolioPageSelect<false> | PortfolioPageSelect<true>;
    'catalog-page': CatalogPageSelect<false> | CatalogPageSelect<true>;
    'blog-page': BlogPageSelect<false> | BlogPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  category?: string | null;
  publishedAt?: string | null;
  excerpt: string;
  coverImage?: (number | null) | Media;
  content: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug: string;
  order: number;
  featured?: boolean | null;
  showOnServicesPage?: boolean | null;
  icon: 'home' | 'box' | 'calendar' | 'chat' | 'doc' | 'hardhat' | 'light' | 'plan' | 'shield' | 'team' | 'wrench';
  href?: string | null;
  previewImage?: (number | null) | Media;
  shortDescription: string;
  description?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories".
 */
export interface PortfolioCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  h1?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  heroImage?: (number | null) | Media;
  showInNavigation?: boolean | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Свяжите карточку портфолио с проектом каталога, чтобы кнопка вела на правильную страницу.
   */
  catalogItem?: (number | null) | Catalog;
  /**
   * Посадочная категория портфолио. Используется для вкладок на главной и страниц /portfolio/category/...
   */
  category: number | PortfolioCategory;
  order: number;
  location?: string | null;
  projectArea?: number | null;
  previewImage?: (number | null) | Media;
  /**
   * Дополнительные фотографии выполненной работы.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  summary: string;
  description?: string | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog".
 */
export interface Catalog {
  id: number;
  title: string;
  slug: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  itemKey: string;
  showInCatalog?: boolean | null;
  isHit?: boolean | null;
  /**
   * Категория посадочной страницы. Используется для выпадающего меню каталога и фильтрации карточек.
   */
  landingCategory?: (number | null) | CatalogCategory;
  order: number;
  previewImage?: (number | null) | Media;
  detailImage?: (number | null) | Media;
  /**
   * Добавляйте сюда все фотографии проекта. Количество фото в карточке каталога считается по этому списку.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Стоимость в рублях, например 18100000
   */
  price?: number | null;
  /**
   * Площадь дома в м²
   */
  area?: number | null;
  /**
   * Количество этажей
   */
  floors?: number | null;
  /**
   * Количество комнат
   */
  rooms?: number | null;
  cardSummary?: string | null;
  description: string;
  /**
   * Пункты, которые выводятся в карточке проекта в блоке преимуществ.
   */
  advantages?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Планировки и генпланы, которые выводятся внутри карточки проекта.
   */
  layouts?:
    | {
        title: string;
        meta?: string | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Загрузите GLB/GLTF модель дома для интерактивного 3D-просмотра в карточке проекта.
   */
  model3d?: (number | null) | Media;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-categories".
 */
export interface CatalogCategory {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  h1?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  heroImage?: (number | null) | Media;
  showInHeader?: boolean | null;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  name: string;
  caption?: string | null;
  avatar?: (number | null) | Media;
  video?: (number | null) | Media;
  poster?: (number | null) | Media;
  rating: number;
  text: string;
  order: number;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  description?: string | null;
  avatar?: (number | null) | Media;
  order: number;
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies".
 */
export interface Vacancy {
  id: number;
  title: string;
  slug: string;
  order: number;
  published?: boolean | null;
  salary?: string | null;
  employment?: string | null;
  location?: string | null;
  summary: string;
  responsibilities?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  conditions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests".
 */
export interface Request {
  id: number;
  requestType: 'estimate' | 'callback' | 'message';
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  service?: string | null;
  message?: string | null;
  sourcePage?: string | null;
  status: 'new' | 'processing' | 'done';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'portfolio-categories';
        value: number | PortfolioCategory;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'catalog-categories';
        value: number | CatalogCategory;
      } | null)
    | ({
        relationTo: 'catalog';
        value: number | Catalog;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'vacancies';
        value: number | Vacancy;
      } | null)
    | ({
        relationTo: 'requests';
        value: number | Request;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  category?: T;
  publishedAt?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  featured?: T;
  showOnServicesPage?: T;
  icon?: T;
  href?: T;
  previewImage?: T;
  shortDescription?: T;
  description?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-categories_select".
 */
export interface PortfolioCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  h1?: T;
  seoTitle?: T;
  seoDescription?: T;
  heroImage?: T;
  showInNavigation?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  catalogItem?: T;
  category?: T;
  order?: T;
  location?: T;
  projectArea?: T;
  previewImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  summary?: T;
  description?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-categories_select".
 */
export interface CatalogCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  h1?: T;
  seoTitle?: T;
  seoDescription?: T;
  heroImage?: T;
  showInHeader?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog_select".
 */
export interface CatalogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seoTitle?: T;
  seoDescription?: T;
  itemKey?: T;
  showInCatalog?: T;
  isHit?: T;
  landingCategory?: T;
  order?: T;
  previewImage?: T;
  detailImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  price?: T;
  area?: T;
  floors?: T;
  rooms?: T;
  cardSummary?: T;
  description?: T;
  advantages?:
    | T
    | {
        text?: T;
        id?: T;
      };
  layouts?:
    | T
    | {
        title?: T;
        meta?: T;
        image?: T;
        id?: T;
      };
  model3d?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  name?: T;
  caption?: T;
  avatar?: T;
  video?: T;
  poster?: T;
  rating?: T;
  text?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  description?: T;
  avatar?: T;
  order?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vacancies_select".
 */
export interface VacanciesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  order?: T;
  published?: T;
  salary?: T;
  employment?: T;
  location?: T;
  summary?: T;
  responsibilities?:
    | T
    | {
        item?: T;
        id?: T;
      };
  requirements?:
    | T
    | {
        item?: T;
        id?: T;
      };
  conditions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "requests_select".
 */
export interface RequestsSelect<T extends boolean = true> {
  requestType?: T;
  name?: T;
  phone?: T;
  email?: T;
  service?: T;
  message?: T;
  sourcePage?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  companyName: string;
  phonePrimary: string;
  phoneSecondary?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  companyStats?:
    | {
        statKey?:
          | ('builtHomes' | 'estimateDay' | 'happyFamilies' | 'marketYears' | 'warranty' | 'region' | 'custom')
          | null;
        value: string;
        label: string;
        showOnHome?: boolean | null;
        showOnAbout?: boolean | null;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  heroTitle: string;
  heroDescription: string;
  /**
   * Изображение для первого экрана на главной. Если поле пустое, используется текущая картинка.
   */
  heroImage?: (number | null) | Media;
  seoTitle?: string | null;
  seoDescription?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  sectionEyebrows?: {
    about?: string | null;
    projects?: string | null;
    trust?: string | null;
    process?: string | null;
    services?: string | null;
    portfolio?: string | null;
    reviews?: string | null;
    faq?: string | null;
  };
  sectionHeadings?: {
    about?: string | null;
    projects?: string | null;
    trust?: string | null;
    process?: string | null;
    processLead?: string | null;
    services?: string | null;
    portfolio?: string | null;
    reviews?: string | null;
    faq?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Изображение для первого экрана страницы «О нас». Если поле пустое, используется текущая картинка.
   */
  heroImage?: (number | null) | Media;
  intro?: string | null;
  principles?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  faqItems?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  officeAddress: string;
  mapEmbedUrl?: string | null;
  companyDetails?: {
    legalName?: string | null;
    inn?: string | null;
    ogrn?: string | null;
    kpp?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page".
 */
export interface PortfolioPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-page".
 */
export interface CatalogPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page".
 */
export interface BlogPage {
  id: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Добавьте несколько роликов для верхнего блока блога. Можно указать прямую ссылку на видеофайл или ссылку на Instagram, TikTok, YouTube Shorts.
   */
  instagramVideos?:
    | {
        label: string;
        title: string;
        instagramUrl?: string | null;
        videoUrl?: string | null;
        posterImage?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  companyName?: T;
  phonePrimary?: T;
  phoneSecondary?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  companyStats?:
    | T
    | {
        statKey?: T;
        value?: T;
        label?: T;
        showOnHome?: T;
        showOnAbout?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  heroTitle?: T;
  heroDescription?: T;
  heroImage?: T;
  seoTitle?: T;
  seoDescription?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  sectionEyebrows?:
    | T
    | {
        about?: T;
        projects?: T;
        trust?: T;
        process?: T;
        services?: T;
        portfolio?: T;
        reviews?: T;
        faq?: T;
      };
  sectionHeadings?:
    | T
    | {
        about?: T;
        projects?: T;
        trust?: T;
        process?: T;
        processLead?: T;
        services?: T;
        portfolio?: T;
        reviews?: T;
        faq?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  heroImage?: T;
  intro?: T;
  principles?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  faqItems?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page_select".
 */
export interface ContactsPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  officeAddress?: T;
  mapEmbedUrl?: T;
  companyDetails?:
    | T
    | {
        legalName?: T;
        inn?: T;
        ogrn?: T;
        kpp?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-page_select".
 */
export interface PortfolioPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-page_select".
 */
export interface CatalogPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-page_select".
 */
export interface BlogPageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  subtitle?: T;
  seoTitle?: T;
  seoDescription?: T;
  instagramVideos?:
    | T
    | {
        label?: T;
        title?: T;
        instagramUrl?: T;
        videoUrl?: T;
        posterImage?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}